### ISSUE TITLE
problem with embedding dimension

### ISSUE THREAD

**Issue by tareeesh2001** [AIAnytime/Haystack-and-Mistral-7B-RAG-Implementation#2]
**intially i've run ingest.py and faced the following error:**
RuntimeError: Embedding dimensions of the model (384) don't match the embedding dimensions of the document store (768). Initiate WeaviateDocumentStore again with arg embedding_dim=384.

**upon changing the embedding_dim from 768 to 384 at line 12 in ingest.py; this is error which i'm facing:**
Traceback (most recent call last):
  File "/Users/sairohith/Downloads/Haystack-and-Mistral-7B-RAG-Implementation/ingest.py", line 60, in <module>
    document_store.update_embeddings(retriever)
  File "/Users/sairohith/Downloads/Haystack-and-Mistral-7B-RAG-Implementation/.venv/lib/python3.11/site-packages/haystack/document_stores/weaviate.py", line 1525, in update_embeddings
    self.weaviate_client.data_object.update({}, class_name=index, uuid=doc.id, vector=emb)
  File "/Users/sairohith/Downloads/Haystack-and-Mistral-7B-RAG-Implementation/.venv/lib/python3.11/site-packages/weaviate/data/crud_data.py", line 266, in update
    raise UnexpectedStatusCodeException("Update of the object not successful", response)
weaviate.exceptions.UnexpectedStatusCodeException: Update of the object not successful! Unexpected status code: 500, with response body: {'error': [{'message': 'msg:repo.merge code:500 err:merge into index document: update local object: shard="iamYdcK7NLPW": Validate vector index for update of 174af3b8-d99f-2b7b-6824-7045bc59d31d: new node has a vector with length 384. Existing nodes have vectors with length 768'}]}.

**Can anyone help me resolve this error?**

**Comment by mahitha-ada** [comment]
Hi I did this first curl -X DELETE "http://localhost:8080/v1/schema/Document" restart docker container and change embedding_dim to 384  document_store = WeaviateDocumentStore(
    host='http://localhost', port=8080, embedding_dim=384) it worked for me.

**Comment by tareeesh2001** [comment]
**hi @sandeesaripalli 
thank you for your help.
came up with anonther error:**
raise WeaviateStartUpError(
weaviate.exceptions.WeaviateStartUpError: Weaviate did not start up in 5 seconds. Either the Weaviate URL http://localhost:8080 is wrong or Weaviate did not start up in the interval given in 'startup_period'.
**Do u have a solution for this?**

**Comment by suyogpardeshi** [comment]
where we can access Pypdf file, in repo is not their...?
